# Final Project

### Import Dependencies CSV's

In [3]:
import pandas as pd

In [4]:
var_serv_df = pd.read_csv("var_service_FINAL_PROJECT.csv")
var_serv_df

,COMPANY,CUST #,SERV FIRST NAME,SERV LAST NAME,CYCLE,ROUTE,DAY,RTE SEQ#,QTY,SIZE,...,PHONE #3 TYPE,SERVICE COUNTY,SERV MISC FLAG,BILL MISC FLAG,LONGITUDE,LATITUDE,MATERIAL,START SERVICE DATE,END SERVICE DATE,GENERAL EMAIL
0,1,98,NaN,FAST & EASY MART 56,CA,23,THU,250,1,4Y,...,NaN,NaN,NaN,NaN,-122.580120,38.575407,NaN,00/00/0000,00/00/0000,NaN
1,1,98,NaN,FAST & EASY MART 56,CA,44,TUE,60,1,4Y,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00/00/0000,00/00/0000,NaN
2,1,98,NaN,FAST & EASY MART 56,CA,44,FRI,50,1,4Y,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00/00/0000,00/00/0000,NaN
3,1,218,NaN,EHLERS ESTATE,CA,44,WED,100,1,4Y,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00/00/0000,00/00/0000,maureen@ehlersestate.com
4,1,218,NaN,EHLERS ESTATE,CA,23,WED,160,1,4Y,...,NaN,NaN,NaN,NaN,-122.497845,38.531887,NaN,00/00/0000,00/00/0000,maureen@ehlersestate.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3684,1,61031,BILL,SQUIRE,CA,65,THU,2610,3,96,...,NaN,NaN,NaN,NaN,-122.575385,38.578162,NaN,00/00/0000,00/00/0000,NaN
3685,1,61096,NaN,POPE VALLEY POST OFFICE,CA,21,FRI,340,1,CT,...,NaN,NaN,NaN,NaN,-122.428386,38.615222,NaN,00/00/0000,00/00/0000,NaN
3686,1,61096,NaN,POPE VALLEY POST OFFICE,CA,62,FRI,720,1,96,...,NaN,NaN,NaN,NaN,-122.427635,38.615527,NaN,00/00/0000,00/00/0000,NaN
3687,1,61706,NaN,P D PROPERTIES,CA,23,THU,180,1,2Y,...,NaN,NaN,NaN,NaN,-122.581514,38.580448,NaN,00/00/0000,00/00/0000,NaN
3688,1,61706,NaN,P D PROPERTIES,CA,61,THU,100,3,96,...,NaN,NaN,NaN,NaN,-122.581514,38.580448,NaN,00/00/0000,00/00/0000,NaN

In [5]:
var_cust_df = pd.read_csv("var_cust_Final_Project.csv")
var_cust_df

,CO,CUST#,CUSTOMER NAME,SERVICE NAME,TAX BODY,CYCLE,MTH$,BAL DUE,UNAPPLIED,CURRENT,...,PRICE LIST,CREDIT LIMIT,AREA CD#3,PHONE #3,SERVICE COUNTY,SERV MISC FLAG,BILL MISC FLAG,GENERAL EMAIL,BILLING EMAIL,F/C FLAG
0,1,82,LYNN & CHRIS WEBER,LYNN & CHRIS WEBER,S,TA,0.00,0.00,NaN,0.00,...,S,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y
1,1,98,FAST & EASY MART 56,FAST & EASY MART 56,C,CA,888.98,963.98,NaN,963.98,...,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y
2,1,218,EHLERS ESTATE,EHLERS ESTATE,SC,CA,965.40,965.40,NaN,965.40,...,CO,NaN,NaN,NaN,NaN,NaN,NaN,maureen@ehlersestate.com,accounting@ehlersestate.com,Y
3,1,345,KELHAM WINERY,KELHAM WINERY,SC,CA,890.40,980.40,NaN,980.40,...,CO,NaN,NaN,NaN,NaN,NaN,NaN,info@KelhamVineyards.com,info@KelhamVineyards.com,Y
4,1,369,NAPA COUNTY FIRE DEPT,RUTHERFORD FIRE DEPT,SC,CA,44.86,44.86,NaN,44.86,...,CO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1051,1,60891,ANGWIN VILLAGE CHURCH,ANGWIN VILLAGE CHURCH,AC,CA,147.63,147.63,NaN,147.63,...,CO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y
1052,1,61031,BILL SQUIRE,BILL SQUIRE,C,CA,311.79,311.79,NaN,311.79,...,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y
1053,1,61096,POPE VALLEY POST OFFICE,POPE VALLEY POST OFFICE,PV,CA,174.80,352.22,NaN,177.42,...,PV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y
1054,1,61706,P D PROPERTIES,P D PROPERTIES,CC,CA,482.56,482.56,NaN,482.56,...,CO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y
1055,1,9999999,UPPER VALLEY YARD ACCOUNT,UPPER VALLEY YARD ACCOUNT,S,CM,0.00,0.00,NaN,0.00,...,CO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N